spring:
  application:
    name: notesbook

  datasource:
    url: jdbc:postgresql://localhost:5432/notesbook
    username: cursework
    password: cursework

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    path: logs
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
